### ISSUE TITLE
Component Values?

### ISSUE THREAD

**Issue by BGR360** [moffenzeefmodular/GMO#1]
Hello Moffenzeefs!

First of all, thank you so much for open sourcing all of the information that you have.

I do SDIY, and I would like to try to make a DIY clone of the GMO for my personal rack, perhaps using a Teensy LC if it will work. If this venture succeeds, I may want to publish a PCB design and sell some. If I decide I want to do this, I will definitely come to you first and ask permission / discuss profit sharing.

I have looked briefly at the schematic for the GMO, and it does not appear to denote particular values for some of the components. I hope you can help me figure out what components would be suitable for the following unmarked symbols in the GMO schematic:

*Op Amps*
- U1 is a quad op amp that buffers the incoming CVs. Would a TL074 be suitable?
- U2 is a quad op amp used to buffer the audio output and various voltage references. Would a TL074 be suitable?

*Diodes*
- The CV clipping diodes on each input are not specified. Would any fast switching diode like the 1N4148 or 1N914 be suitable?
- The reverse power protecting diodes are not specified. Other modules such as those from GMSN! use 1N5817 schottky rectifier diodes. Would these be suitable?
- I presume 1N4148 would be suitable for D6

*Regulators / Vrefs*
- The 5V regulator is unmarked. What part would you recommend?
- The 5V regulator symbol appears to be surrounded by two small unmarked capacitors. Are these part of the symbol, or are these bypass capacitors that need to be added near the regulator?
- The -2v5 voltage reference is unmarked. What part would you recommend?

I hope you will take the time to assist me with this. I would very appreciative. Hope to hear from you soon!

**Comment by moffenzeefmodular** [comment]
You're free to clone GMO for yourself, but distributing PCBs for sale of your clone is against the CC-BY-NC-SA license.  

That being said, the schematics were published to help you with your own projects and endeavors. You are certainly free to use as much of the circuit and code as you want in your own original design. I will be glad to help you with this additional information under the mutual understanding that this project is only for you and that you respect my wishes to not release it commercially. This is a very small community and I assure you that I'll find out if you do :D. 

Some answers to your questions:

-In it's current state, GMO will not run on Teensy LC, you are required to use Teensy 3.2. 
-All op amps in the circuit are TL07x 
-The CV clipping diodes can be any general purpose switching diode but schottky diodes are much more preferred due to their better forward voltage rating (they clamp harder).
-The reverse power protection diodes are 60v 1A B160-13-F schottkeys, different from the ones for CV clamping. 
-The 5v regulator can be a 7805 or a 78L05, either one should suffice for this project (it's pretty low current draw) 
-Ignore those two symbols on the regulator they're just supposed to indicate that you need bypass caps
-The -2v5 reference is just the inverse of the 2v5 regulator. LM4040. 

Cheers,
Ross
